### ISSUE TITLE
#Q&A Inquiry Regarding Publishing Expo React Native App on F-Droid

### ISSUE THREAD

**Issue by uyriq** [Alovoa/alovoa-expo#38]
Dear Alovoa Team,

I recently explored your application repository and noticed that you are using Expo React Native. I am genuinely intrigued by how you successfully published your [application on F-Droid](https://f-droid.org/it/packages/com.alovoa.expo/) . I am currently working on creating my own workflow for publishing an application, but I’m facing challenges due to Expo’s unsupported components. It appears that Expo Go cannot be directly published on F-Droid.

Could you kindly share any insights, documentation, or tutorials that might guide me in achieving a similar outcome? Your expertise would be greatly appreciated.

**Comment by Nonononoki** [comment]
Basically you need to fork all expo-* dependencies you use that use proprietary Google libraries and remove it. This is true for expo-application and expo-location, you can see my forks in the script folder. For further info just ask the helpful people on F-droid. Be aware that you need to fork them each time you update expo, it's rather tedious because the source code is in a mono repo.
